### ISSUE TITLE
Possible bug with Loop

### ISSUE THREAD

**Issue by JamesZFS** [wjakob/enoki#59]
Not sure if it's a bug or reproducible, but when I try this code snippet, it gets stuck at the point of compiling the kernel at random probability. (in the worst case takes around 10 seconds to finish, strangely)
```python
import drjit as dr
from drjit.llvm.ad import Int, UInt, Float, Loop

i = dr.zeros(Int, 10)
j = dr.zeros(Int, 10)

dr.make_opaque(i, j)  # commenting this line, it runs super fast

loop = Loop("MyLoop", lambda: (i, j))
while loop(i < 10):
    j += i
    i += 1

assert i == Int([10]*10)
assert j == Int([45]*10)
```
It could be an issue related to using `Loop` and `make_opaque`.

**Comment by njroussel** [comment]
Thanks for reporting this @JamesZFS

I haven't figured out what was causing this issue/behaviour. Here's a few notes on what I observed, in case I pick this back up again at some point.

Behavior:
* I can reproduce the behavior consistently on my machine. I'd say it happens about 1 out of 5 times. There is definitely a large variance in the overall runtime of the script.
* I could only reproduce this with `LLVM` variants.
* Whether the kernels are read from the cache or not, doesn't influence this behaviour. The slowdown seems to happen just as frequently.
* Without the call to `dr.opaque`, there is barely any change in runtime speed and it runs approximately 10 times faster than the fastest runs with `dr.opaque`.

Cause:
* The slowdown comes from the kernel execution rather than the backend compilation. I determined this by using the `KernelHistory` feature and also inserting my own timestamps right before and after the kernel execution (in C++ `Task`).
* Profiling information is limited: it indeed shows that most of the time is spent inside the kernel.
* When running everything on the main thread (`dr.set_thread_count(0)`), the behaviour is still reproduce-able. Therefore, this doesn't seem like a threading issue related to `nanothread`. In fact, I even changed the LLVM kernel execution to run directly in `drjit` rather than being submitted to the `nanothread` worker pool and could still reproduce the behaviour.
* The LLVM IR is always exactly the same. The compiled binary is also always the same.
* When inspecting the x86 instructions, the difference between the two kernels (with/without the call to `dr.opaque`) are only a few additional `mov` instructions to initialize `i` and `j` in the `dr.opaque` version.

**Comment by wjakob** [comment]
The issue only appears to happen for SIMD packets that are not fully filled (for example, 10 lanes on 8-wide or 16-wide AVX[512]). That makes me suspect that there is some undefined behavior caused by the remainder of the packet, and surprisingly it indeed seems that we missed this case.

Here is a tentative patch:

```diff
diff --git a/include/drjit/loop.h b/include/drjit/loop.h
index ed42ff0..ea9331d 100644
--- a/include/drjit/loop.h
+++ b/include/drjit/loop.h
@@ -216,10 +216,14 @@ struct Loop<Mask, enable_if_jit_array_t<Mask>> {
     }
 
     bool operator()(const Mask &cond) {
+        Mask cond2 = cond;
+        if (Backend == JitBackend::LLVM)
+            cond2 &= Mask::steal(jit_var_mask_peek(Backend));
+
         if (m_record)
-            return cond_record(cond);
+            return cond_record(cond2);
         else
-            return cond_wavefront(cond);
+            return cond_wavefront(cond2);
     }
 ```

**Comment by njroussel** [comment]
Ohh, indeed!
With this fix, I can see in the LLVM IR how the loop condition has this mask applied. That was totally missing before, and so the remainder of the packet was being used in all operations including the loop condition.

As a sanity check, running the script with `i` and `j` as 8 or 16-wide wide arrays never produced the random slowdowns before applying the fix.
